# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Botoes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 700)
        self.Cientifica = QtWidgets.QPushButton(Dialog)
        self.Cientifica.setGeometry(QtCore.QRect(70, 110, 451, 191))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.Cientifica.setFont(font)
        self.Cientifica.setObjectName("Cientifica")
        self.Convencional = QtWidgets.QPushButton(Dialog)
        self.Convencional.setGeometry(QtCore.QRect(70, 400, 451, 191))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.Convencional.setFont(font)
        self.Convencional.setObjectName("Convencional")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Cientifica.setText(_translate("Dialog", "Científica"))
        self.Convencional.setText(_translate("Dialog", "Convencional"))
